export const BRICS = [
  "Brazil",
  "Russian Federation",
  "India",
  "China",
  "South Africa",
  "Iran",
  "Egypt",
  "Ethiopia",
  "Argentina",
  "Saudi Arabia",
  "UAE",
];

export const NATO = [
  "Albania",
  "Belgium",
  "Bulgaria",
  "Canada",
  "Croatia",
  "Czech Republic",
  "Denmark",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hungary",
  "Iceland",
  "Italy",
  "Latvia",
  "Lithuania",
  "Luxembourg",
  "Montenegro",
  "Netherlands",
  "North Macedonia",
  "Norway",
  "Poland",
  "Portugal",
  "Romania",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Sweden",
  "Turkey",
  "United Kingdom",
  "United States of America",
];

export const Continents: Record<string, string[]> = {
  Africa: [
    "South Africa",
    "Nigeria",
    "Egypt",
    "Ethiopia",
    "Kenya",
    "Algeria",
    "Morocco",
    "Ghana",
    "Angola",
    "Tanzania",
  ],
  Asia: [
    "China",
    "India",
    "Japan",
    "South Korea",
    "Indonesia",
    "Saudi Arabia",
    "Iran",
    "Viet Nam",
    "Thailand",
    "Philippines",
  ],
  Europe: [
    "France",
    "Germany",
    "Italy",
    "Spain",
    "United Kingdom",
    "Russian Federation",
    "Poland",
    "Netherlands",
    "Ukraine",
    "Sweden",
  ],
  "North America": ["United States", "Canada", "Mexico", "Cuba", "Guatemala"],
  "South America": ["Brazil", "Argentina", "Colombia", "Chile", "Peru"],
  Oceania: ["Australia", "New Zealand", "Papua New Guinea", "Fiji", "Samoa"],
};
